name: 'Suggest Related Links'

on:
  issues:
    types:
      - opened
      - edited
  workflow_dispatch:
  schedule:
    - cron: '13 13 * * */7'

jobs:
  action:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Setup Python
        if: github.event_name == 'issues'
        uses: actions/setup-python@v2.1.2
        with:
          python-version: '3.8'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/actions-suggest-related-links-tmp
          key: ${{ runner.os }}-action-${{ hashFiles('~/actions-suggest-related-links-tmp/training-data.json') }}
          restore-keys: |
            ${{ runner.os }}-action-

      - uses: peaceiris/actions-suggest-related-links@v1.1.0

      - name: fastText
        if: github.event_name == 'issues'
        run: |
          git clone https://github.com/peaceiris/actions-suggest-related-links.git ~/asrl
          cd ~/asrl/models/fasttext
          git checkout v1.1.0
          cp ~/actions-suggest-related-links-tmp/{training-data.json,input.txt} .
          make train
          cp ./suggestions.json ~/actions-suggest-related-links-tmp/

      - uses: peaceiris/actions-suggest-related-links@v1.1.0
        with:
          mode: 'suggest'
          repository: 'peaceiris/actions-gh-pages'
          unclickable: true
